---
title: "Choosing the Best Pokemon Character"
author: "David Jackson"
date: "4/25/2021"
output: 
  html_document: 
    fig_width: 9
    fig_height: 7
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(scales)
library(dplyr)
library(tidyr)
library(dlookr)
library(flextable)
# library(ggtext)
```

## Descriptive Stats

```{r}
rm(list=ls())
pokemon <- read.csv("./ChoosingYourFirstPokemon.csv") 
pokemon_df <- pokemon %>% filter(Type.1 %in% c("Grass","Water","Fire") & Generation ==1)

pokemon_df <- pokemon_df %>% filter(!Name %in% c("VenusaurMega Venusaur","CharizardMega Charizard X",
                                             "CharizardMega Charizard Y","GyaradosMega Gyarados",
                                             "BlastoiseMega Blastoise","SlowbroMega Slowbro"))

```
```{r}
pokemon_df %>% select(Total:Speed) %>% diagnose_numeric() %>% flextable()
```


```{r}
barplot(table(pokemon_df$Type.1),main="Count by Charactor Type")
```

```{r}
pokemon_db <- pokemon_df %>% filter(Name %in% c("Bulbasaur","Squirtle","Charmander") & Generation ==1)
poke_across <- pokemon_df %>% group_by(Type.1) %>%
  summarise(across(Total:Speed,list(Mean = mean, Median= median )))
poke_longer <- poke_across %>% pivot_longer(Total_Mean:Speed_Median,values_to = "Skills")
```

```{r}
pokemon_fire <- pokemon_df  %>% 
  filter(Type.1 == "Fire") %>% 
  mutate(Name.fill = if_else(Name == "Charmander", TRUE, FALSE)) 
ggplot(data = pokemon_fire, aes(x = Total, 
                                 y = Name, 
                                 fill = Name.fill)) + 
  geom_col() +
  scale_fill_discrete(type = c("gray50","red")) +
  labs(title = "Comparing Character's from Type.1 of Fire") +
  geom_vline(data = pokemon_fire, aes(xintercept = mean(Total)))
```

### Plot of Water

```{r}
pokemon_water <- pokemon_df  %>% 
  filter(Type.1 == "Water") %>% 
  mutate(Name.fill = if_else(Name == "Squirtle", TRUE, FALSE)) 
ggplot(data = pokemon_water, aes(x = Total, 
                                 y = Name, 
                                 fill = Name.fill)) + 
  geom_col() +
  scale_fill_discrete(type = c("gray50","red")) +
  labs(title = "Comparing Character's from Type.1 of Water") +
  geom_vline(data = pokemon_water, aes(xintercept = mean(Total)))
```

```{r}
pokemon_grass <- pokemon_df  %>% 
  filter(Type.1 == "Grass") %>% 
  mutate(Name.fill = if_else(Name == "Gloom", TRUE, FALSE)) 
ggplot(data = pokemon_grass, aes(x = Total, 
                                 y = Name, 
                                 fill = Name.fill)) + 
  geom_col() +
  scale_fill_discrete(type = c("gray50","red")) +
  labs(title = "Comparing Character's from Type.1 of Grass") +
  geom_vline(data = pokemon_grass, aes(xintercept = mean(Total)))
```

